### ISSUE TITLE
Var declaration error

### ISSUE THREAD

**Issue by kylescousin** [serpmetrics/smapi-php-sdk#3]
$credentials = self::$_credentials; around line 322

Should be $credentials = $this->_credentials;

And on line 353 it gives error: Access to undeclared static property: App\SMapi::$_http_status
self::$_http_status  should be $this->_http_status ?

**Comment by serpmetrics** [comment]
Thanks for pointing that out - we won't let non-PHP devs update this in future!

**Comment by kylescousin** [comment]
It's possible this was correct syntax in an older PHP version. Thanks for
quick fix!
